#theme: jekyll-theme-merlot

Raw
Blame
History


#

# Website's configuration file.

#



name: Gogul Ilango

description: This blog on Deep Learning, VLSI Design and STA is written by Gogul Ilango. Master VLSI Design, Physical Design, Static Timing Analysis, Deep Learning through my articles, tutorials and resources.

avatar: /images/gogs.jpg

subheading: Personal Website of Gogul Ilango

image: /images/icons/logo.png



footer-links:

  email: gogulilangoswami@gmail.com

  github: Gogul09

  linkedin: Gogulilango

  twitter: gogul_ilango

  stackoverflow:

  youtube: channel/UC_7qnwOlGBTjnt4TxPMureQ



google_analytics: UA-93019594-1

url: "https://gogul.dev"

baseurl: ""



permalink: /:title/

version: v1.2.0

kramdown:

  input: GFM

  syntax_highlighter: rouge

  syntax_highlighter_opts:

    css_class: 'highlight'

    span: 

      line_numbers: false

    block:

      line_numbers: true

      start_line: 1



sass:

  style: :compressed



gems:

  - jekyll-sitemap

  - jekyll-feed

  - jekyll-seo-tag



exclude:

  - Gemfile

  - Gemfile.lock

  - LICENSE

  - README.md

  - CNAME



plugins: 

  - jekyll-paginate

  - jekyll-seo-tag

  - jekyll-sitemap



paginate: 4

excerpt_separator: <!--more-->
